### ISSUE TITLE
Style Guide: Please transfer all info to <code> style guide

### ISSUE THREAD

**Issue by EBUJOLD** [nickcounts/Arduino-Lessons#1]
xChips instead of x-Chips, X-Chips, X-CHIPS, XCHIPS, XChips
xSystem when referring to the whole system of stuff. "The xSystem is designed to ...."

**Comment by EBUJOLD** [comment]
Capitalize All Important Words in a Title or Header

Including numbered lists with a paragraph below the number
1. Header Title
Wordhsbdjsbdosnbajndbjksnshjd
2. Header Title
Bsjajebdhjsksnsjzxmsksbdn
3. Header Title
Ndjajsbdjdksndjdkdndjdkdm

**Comment by EBUJOLD** [comment]
Put "Pro-tips" (Notes, hints, reminders etc) in a quote box.

**Comment by nickcounts** [comment]
Can you clarify "Including numbered lists with a paragraph below the number (because these are basically headers)" ? I'm not sure I understand what you're trying to say

**Comment by EBUJOLD** [comment]
There was a spot in the documents where there was a numbered list, and the numbered part was a kind of header to a paragraph below. All under the same number. 

1. Header Title
Wordhsbdjsbdosnbajndbjksnshjd
2. Header Title
Bsjajebdhjsksnsjzxmsksbdn
3. Header Title
Ndjajsbdjdksndjdkdndjdkdm

**Comment by EBUJOLD** [comment]
But this:
1. I like jam and toast
2. Because toast is great
3. And so is jam

Would not be capitalized

**Comment by EBUJOLD** [comment]
XinaBox is the preferred spelling, found on Matt Craft's materials

**Comment by nickcounts** [comment]
Gotcha - makes good sense since they function as numbered subheadings.

I think this guide would be useful to us as an actual page on either the wiki, or as a .md file in the code repo.

You can write a style guide using the style lol

**Comment by EBUJOLD** [comment]
Can I make it private to just us?

**Comment by nickcounts** [comment]
Anything you put in the wiki is accessible through the "Pages" sidebar, although it's collapsed by default since we have a custom sidebar. That's probably fine. If you put it in the code side of the repository, then it won't be on the wiki, but it'll be a little trickier for us to view it. 

You could put it in the readme.md ? that gets displayed at the bottom of the repo page

**Comment by nickcounts** [comment]
looks like if you click a .md file from the repo, GitHub will render it for you... kinda nice

https://github.com/nickcounts/Arduino-Lessons/blob/master/Test%20Style%20Guide.md

**Comment by nickcounts** [comment]
loving the style guide, I think that'll be very helpful for us.

Maybe it's just me, but when I see XinaBox I hear "Zina Box" :p

**Comment by EBUJOLD** [comment]
@Not just you! I sometimes think Christina Box.  From "Xtina Agulera"
Nobody asked us what to call it clearly lol

**Comment by jtsingh7** [comment]
all of this information is now in the style guide markdown file so I am closing the issue
