### ISSUE TITLE
LED Colors

### ISSUE THREAD

**Issue by EBUJOLD** [nickcounts/Arduino-Lessons#12]
Did we figure out how to do different colors on the LEDs?

**Comment by nickcounts** [comment]
For the CW01, the RGB LED colors are as follows:

| Color       | Pin |
|----------|----|
| RED         | 12  |
| GREEN    | 13  |
| BLUE       | 5    |

Access to LED1 on IP01 is not exposed. If you want to pursue it a good starting point is the [data sheet](http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf) for the FTDI chip FT232RL.

Check out [page 32](http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf) - it looks like it's only for transmit/receive feedback.

**Comment by EBUJOLD** [comment]
I think we've worked this out. 
If we make a lab for Blink lab, we might want to include the datasheet. might.
