### ISSUE TITLE
Project Task Organization - Split wiki and code tasks?

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/Arduino-Lessons#14]
I'm easy either way - do we want to have one project for wiki development and one for code?

If not, we should think about how to clearly distinguish between wiki and code tasks. Either keeping wikis as notes and code as issues, or making everything an issue with appropriate names and adding tags... there are a lot of options.

Thoughts?

**Comment by EBUJOLD** [comment]
how bout nah?
