### ISSUE TITLE
Lab 4: Temperature over Serial

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/Arduino-Lessons#2]

**Comment by EBUJOLD** [comment]
Why are these here? I don't understand them.

**Comment by nickcounts** [comment]
These are tracking items that are part of the "Projects" feature for managing development tasks. Let's leave this open for now and we'll tag up later to see if we want to use this or not.

**Comment by EBUJOLD** [comment]
I'm going to try writing up the code first, then we'll build a lesson around it.

**Comment by EBUJOLD** [comment]
Reviewed and preliminarily (It's a word, trust me) tested.
