### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by jtsingh7** [nickcounts/Arduino-Lessons#20]
after we finish all the labs and other pages

**Comment by EBUJOLD** [comment]
What do you mean? Expand and tag pls :)

**Comment by jtsingh7** [comment]
for the page called "home" we should just make sure all the links work and are properly titled after we finish making the labs. And we could maybe add more to the opening paragraph

**Comment by EBUJOLD** [comment]
"bug" fixed.
