### ISSUE TITLE
Lab 3: Pressure and Altitude

### ISSUE THREAD

**Issue by jtsingh7** [nickcounts/Arduino-Lessons#21]
made a new page for lab 3. Jotting down ideas for the flow of the lab. Thinking of talking about libraries for the Deeper Understanding part. Lab will go over how the getAltitude() function simply performs an equation on the pressure reading in the xChip library in order to get an altitude value. Thinking of sticking with OLED output and going to serial stuff in lab 4

**Comment by EBUJOLD** [comment]
Looks good, since this is the introduction to the temperature sensor I'm not going to include the light sensor. gucci?

I'll try and have the code written today.

**Comment by jtsingh7** [comment]
I was actually thinking we could leave the light sensor attached for this lab and take the UVA/UVB measurements. Would get a good weather theme going and give them a chance to use all five chips at once? What do you think

**Comment by EBUJOLD** [comment]
They will definitely get to use all the chips and make a weather station, but learning the UVA/UVB and Temp/humidity/altitude all at once is a lot.
And we have ~10 labs to make, so let's drag this out lol. 
let's have a pow-wow and work on the outline.

**Comment by jtsingh7** [comment]
To do:
Read through and edit
Add DU Section
Make sure all the internal links work

**Comment by nickcounts** [comment]
This looks like a solid lab and a good writeup. I added the Arduino styling to the code examples and threw in a photo for 💩&😂

I tested the code samples - everything seems to work.

No reflection on this section, but since we have 3 sets of programmers' code now we might want to think about some code style too... I'm going to open an item so we can hash it out somewhere else

**Comment by EBUJOLD** [comment]
Finished review. It will probably need another look over with another set of eyes, I made a fair amount of changes. 
Explanations were good, but written at a college level so I simplified the language in places. I'm going to talk to our Elementary school liaison (everett) and make sure that we are writing appropriately.

**Comment by EBUJOLD** [comment]
Reviewed. Ready for the people.
