### ISSUE TITLE
Code Style Guide for our sample code

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/Arduino-Lessons#22]
Let's think about how we want to style our code and throw together a quick and dirty style guide. We can reformat existing code in the wiki and the repo. It doesn't have to be as intense as [PEP-8](https://www.python.org/dev/peps/pep-0008/) - but if you've never thought about code style it's worth a skim.

I'm thinking specifically about how we want to handle:

* comments
* indentations
* blank lines between commands
* variable naming conventions? (so far I think it's been a non-issue)
* maximum line length? (for ease of reading/viewing/printing/editing.... )

Maybe standardize what goes in the comments at the beginning of our examples.

**Comment by EBUJOLD** [comment]
I started this in the style guide. Maybe breaking it ut to it's own file and then beef it up

**Comment by nickcounts** [comment]
Added function definition guide complete with spacing and curly braces...

now I want curly fries - and desperately want to know what rainbow snakes is

**Comment by EBUJOLD** [comment]
Style guide created. Issue closed.
