### ISSUE TITLE
Make Code Folders

### ISSUE THREAD

**Issue by EBUJOLD** [nickcounts/Arduino-Lessons#23]
Dunno how to make folders in the <code> section to make a file structure like we talked about.
Folders that'd be cool:

>Bonus Code

>ThinSat Labs
>> Lab 1
>> Lab 2
>> etc

> Arduino Labs
Just dump that shit in here, there isn't much

Keep our reference files outside of folders. Thoughts?

**Comment by nickcounts** [comment]
I like that - what do you think about including "Bonus Code" in the "ThinSat Labs" folder?

I'm easy either way. I agree with keeping references in the project root folder

**Comment by EBUJOLD** [comment]
Finally Did it
