### ISSUE TITLE
Bonus Lab 5

### ISSUE THREAD

**Issue by jtsingh7** [nickcounts/Arduino-Lessons#30]
UV Index

**Comment by jtsingh7** [comment]
current code does a legit calculation and asks user if it's sunny/cloudy/overcast outside to make an adjustment. It'd probably be best to somehow do this outside otherwise I don't know how useful the weather input part is

**Comment by EBUJOLD** [comment]
Could we use the lux sensor to detect brightness?

Emily Bujold

**Comment by EBUJOLD** [comment]
Not gonna happen. Lab deleted.
