### ISSUE TITLE
No data from SN01 on 915MHz band radio firmware

### ISSUE THREAD

**Issue by wdconinc** [nickcounts/Arduino-Lessons#36]
Setup
GS: IP01 (DCE, A, serial connected 115200 8N1), CW01 (FlashTool Xinabox firmware), CR03 (917.5 MHz, CR03_BootCamp_Firmware_V1.200_20170813), OD01
SAT: IP01 (power only), CR03 (id), SW01, SL01, SI01, SN01

Data from SAT SW01, SL01, SI01 appears on dashboard. 

Expected results:
Readout of GNSS module SN01 on SAT should appear as Long and Lat on display OD01, on serial port connected to GS, and on dashboard.

Actual results:
No position info appears on dashboard. Display shows SAT Latitude, SAT Longitude both as UNKNOWN. Serial port shows
```
Satellite_Payload : 
{
"GS": {
  "CW01": {"RSSI":-42,"Chip ID":15691712,"MAC":"5C:CF:7F:EF:6F:C0"},
  "Input": {},
  "Timestamp":{"Created":"2017-11-14T16:04:53"}},
"SAT": {
  "SW01": {"Temperature(C)":23.74,"Humidity(%)":35.28,"Pressure(Pa)":102438.80},
  "SL01": {"Lux":5092.00,"UVA(mW/m^2)":1063.04,"UVB(mW/m^2)":416.19,"UVI":-0.66},
  "PB04": {"Current(mA)":-64513.00,"Voltage(V)":-258.05},
  "SI01": {"G-Force":1.01,"Roll(Deg)":6.40,"Pitch(Deg)":-2.21},
  "OC01": {"Burn Status":"0000"},
  "CR03": {"GS RSSI(dB)":-42,"Satellite RSSI(dB)":-45},
  "Timestamp":{"Captured":"2017-11-14T16:12:12"}}}
[PUBLISHED]
```
indicating that no SN01 is even detected. Attempted this with the other SN01 module in our packet. Notice that it does somehow detect a SAT PB04 and OC01, neither of which are connected.

Debugging is complicated by the absence of firmware source code.

**Comment by nickcounts** [comment]
This looks familiar to me. I believe I had the same issue when we visited W&M for our meeting/demo.

```
Satellite_Payload : 
{
"GS": {
   "CW01": {"RSSI":-51,"Chip ID":1575432,"MAC":"A0:20:A6:18:0A:08"},
   "Input": {"Unit Name":"DemoSat","Organization":"MARS","Location": 
   [36.8856,-76.3068],"Altitude(m)":10},"Timestamp":{"Created":""}},
"SAT": {
   "SW01": {"Temperature(C)":25.12,"Humidity(%)":47.50,"Pressure(Pa)":103242.80},
   "SL01": {"Lux":536.00,"UVA(mW/m^2)":26.09,"UVB(mW/m^2)":24.76,"UVI":0.01},
   "PB04": {"Current(mA)":108.00,"Voltage(V)":2.75},
   "SI01": {"G-Force":1.00,"Roll(Deg)":1.79,"Pitch(Deg)":-15.62},
   "OC01": {"Burn Status":"0000"},
   "CR03": {"GS RSSI(dB)":-35,"Satellite RSSI(dB)":-38},"Timestamp":{"Captured":"2017-10-03T17:47:31"}}}
[PUBLISHED]
```

# Easy Answer First:

I believe if the SN01 does not have an adequate GPS signal then nothing is displayed in the serial debug logs. I know this is not entirely consistent behavior with the remaining chips, as you mentioned, which show dummy values for unconnected hardware.

I will check in with XinaBox to see if this is still on their list of things to address. I had a lengthy email correspondence with them about this very issue.

# The Long Story

The SN01 is built on UBlox, so if you want to really dig in, there is a ton of information out there. You can solder a pair of pads on the back of the xChip that will allow you to connect the SN01 to your IP01 and get serial debugging info directly out of the GPS module.

![img_1966](https://user-images.githubusercontent.com/10506020/32855034-8fcac3ca-ca0e-11e7-8434-366335179a9e.jpeg)

It's a little wonky, but it's totally doable. 

## Serial Parameters that worked for me

- 38400 bps
- 8
- No Parity
- 1 stop bit


Here is a screenshot of output I got when I bridged my debugging pads incorrectly (was effectively in loopback and it's the only screenshot I have available)

<img width="480" alt="pastedgraphic-7" src="https://user-images.githubusercontent.com/10506020/32855148-f5480a32-ca0e-11e7-8a9b-89281a103fce.png">


## More Information:

https://forum.u-blox.com/index.php?qa=1031&qa_1=gptxt-nmea-unknown-msg-meaning

**Comment by wdconinc** [comment]
Ok, that's helpful. I think I figured out the behavior. It seems indeed caused by the lack of GNSS fix and the different behavior for the component. Once I'm outside with it, it seems to work (still shows PB04 even if not connected). In general, I'd feel much more comfortable having the firmware source code or some higher level description of what it's supposed to do. Same thing with CR03 connection: it just outputs "Sent command 1" etc, sometimes "FAILED" but no idea what's actually happening. Makes debugging frustrating... `</rant>`
