### ISSUE TITLE
Lab 2: Light Sensor

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/Arduino-Lessons#6]

**Comment by EBUJOLD** [comment]
Choosing this as lab 2 because it's the same hardware as lab 1. 
Going to have it display over OLED.

**Comment by EBUJOLD** [comment]
Lab is being called "Lab 2: Light Sensor"

**Comment by EBUJOLD** [comment]
Lab 2 Complete. Please test code and setup as well as check for grammar/flow.

**Comment by EBUJOLD** [comment]
has this been reviewed? Is this ready for release?
We should write comments after reviews. I like that this has a "change log"
