### ISSUE TITLE
Lab 5: UV Rays

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/Arduino-Lessons#7]

**Comment by EBUJOLD** [comment]
Display data on serial monitor and OLED.

OLED should display something different than serial (good idea?), possibly a logic statement.

**Comment by EBUJOLD** [comment]
http://media.digikey.com/pdf/Data%20Sheets/Austriamicrosystems%20PDFs/TSL4531.pdf

**Comment by EBUJOLD** [comment]
Done, It feels like a really light lab. Anything that could make it better?

**Comment by nickcounts** [comment]
-100000 points for terrible puns

Do you think we could add something to calculate (roughly) the UV Index or something like that? Maybe adding a derived measurement would fill this out a bit?

I also noticed 3 things to possibly address:

- [x] Image doesn't render (maybe .JPG instead of .jpg)
- [x] `switch` statement example not styled as C++ or Arduino
- [x] `switch` statement example seems to be missing `{ }` - was it intended as pseudocode?

I mostly wanted to use the checkboxes

**Comment by jtsingh7** [comment]
I was gonna make the UV Index calculator for the bonus lab, should we just put it in the actual lab instead?

**Comment by nickcounts** [comment]
Is there a simplified version - like an estimate that's less mathematically complex?

Maybe we could put a simple version in the main lab and go in depth in the DU section

**Comment by EBUJOLD** [comment]
I think the UV index should remain a bonus lab. It's an extensive amount of calculations.

Image fixed. It was the shouting extension. (use .jpg not .JPG)

**Comment by EBUJOLD** [comment]
Snippet fixed. Brackets were left off on accident.

**Comment by nickcounts** [comment]
Fair point - how about adding some reaction/interaction?

We could vary the brightness of the LED based on the ambient lighting - make the LED inversely proportional to the lux.

Or have it fade up/down when there is a big enough lux change...

Or maybe you could find something else fun to do (Party lights, anyone? Rave mode??)

**Comment by EBUJOLD** [comment]
It's UV, but I could do something like that...
bonus lab 0 has party lights
bonus lab 2 has if lights.

update:
I could make a picture of a Sun or something if the UV is high.

**Comment by jtsingh7** [comment]
I like that idea a lot (adjusting LED based on ambient lighting)

**Comment by nickcounts** [comment]
Good point - we might be able to consider big UV changes a sign of indoor/outdoor transition. So maybe something based on that?

A sunburn warning thing? Input your skin type and display a warning level based on exposure? 

Gingers are just SOL

 I dunno, I'm reaching

**Comment by EBUJOLD** [comment]
No that's a real thing and I found a white paper on it, but calculating UV index was such a pain I dropped it.

I'm gonna add a picture of a sun or something on the display, and then a cloud of it's dark. The OLED can do some cool stuff with a bit of effort.

**Comment by EBUJOLD** [comment]
Lab created.
