### ISSUE TITLE
xChip Introduction Finished: Please Review

### ISSUE THREAD

**Issue by EBUJOLD** [nickcounts/Arduino-Lessons#9]
I think it is complete so: 
If everyone could take a look at it and suggest improvements or fix errors that would be groovy.

@jtsingh7 I like the edits you did to it 👍

[xChip Introduction](https://github.com/nickcounts/Arduino-Lessons/wiki/xchip-introduction)

**Comment by jtsingh7** [comment]
i approve

**Comment by nickcounts** [comment]
Looks good to me. I made a few very minor edits - I think it's ready for prime time
